/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 12-jul.-2018 08:47:00 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Objeto_Modulo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Objeto] DROP CONSTRAINT [FK_Objeto_Modulo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleRol_Objeto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Permisos] DROP CONSTRAINT [FK_DetalleRol_Objeto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleRol_Rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Permisos] DROP CONSTRAINT [FK_DetalleRol_Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RolUsuario_Rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioRol] DROP CONSTRAINT [FK_RolUsuario_Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RolUsuario_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsuarioRol] DROP CONSTRAINT [FK_RolUsuario_Usuario]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Modulo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Modulo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Objeto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Objeto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Permisos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Permisos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsuarioRol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsuarioRol]
GO

/* Drop Stored Procedures */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Procedure1]')) 
DROP PROCEDURE [Procedure1]
GO

/* Create Tables */

CREATE TABLE [Modulo]
(
	[modId] varchar(3) NOT NULL,
	[modNombre] varchar(50) NOT NULL
)
GO

CREATE TABLE [Objeto]
(
	[objId] varchar(50) NOT NULL,
	[objNombre] varchar(256) NOT NULL,
	[modId] varchar(3) NOT NULL
)
GO

CREATE TABLE [Permisos]
(
	[rolId] varchar(50) NOT NULL,
	[objId] varchar(50) NOT NULL
)
GO

CREATE TABLE [Rol]
(
	[rolId] varchar(50) NOT NULL,
	[rolNombre] varchar(30) NOT NULL,
	[rolDescripcion] varchar(256) NULL
)
GO

CREATE TABLE [Usuario]
(
	[usrId] varchar(50) NOT NULL,
	[usrPassword] varchar(256) NOT NULL
)
GO

CREATE TABLE [UsuarioRol]
(
	[rolId] varchar(50) NOT NULL,
	[usrId] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Modulo] 
 ADD CONSTRAINT [PK_Modulo]
	PRIMARY KEY CLUSTERED ([modId] ASC)
GO

ALTER TABLE [Objeto] 
 ADD CONSTRAINT [PK_Objeto]
	PRIMARY KEY CLUSTERED ([objId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Objeto_Modulo] 
 ON [Objeto] ([modId] ASC)
GO

ALTER TABLE [Permisos] 
 ADD CONSTRAINT [PK_DetalleRol]
	PRIMARY KEY CLUSTERED ([rolId] ASC,[objId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DetalleRol_Objeto] 
 ON [Permisos] ([objId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DetalleRol_Rol] 
 ON [Permisos] ([rolId] ASC)
GO

ALTER TABLE [Rol] 
 ADD CONSTRAINT [PK_Rol]
	PRIMARY KEY CLUSTERED ([rolId] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([usrId] ASC)
GO

ALTER TABLE [UsuarioRol] 
 ADD CONSTRAINT [PK_RolUsuario]
	PRIMARY KEY CLUSTERED ([rolId] ASC,[usrId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_RolUsuario_Rol] 
 ON [UsuarioRol] ([rolId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_RolUsuario_Usuario] 
 ON [UsuarioRol] ([usrId] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Objeto] ADD CONSTRAINT [FK_Objeto_Modulo]
	FOREIGN KEY ([modId]) REFERENCES [Modulo] ([modId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Permisos] ADD CONSTRAINT [FK_DetalleRol_Objeto]
	FOREIGN KEY ([objId]) REFERENCES [Objeto] ([objId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Permisos] ADD CONSTRAINT [FK_DetalleRol_Rol]
	FOREIGN KEY ([rolId]) REFERENCES [Rol] ([rolId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioRol] ADD CONSTRAINT [FK_RolUsuario_Rol]
	FOREIGN KEY ([rolId]) REFERENCES [Rol] ([rolId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [UsuarioRol] ADD CONSTRAINT [FK_RolUsuario_Usuario]
	FOREIGN KEY ([usrId]) REFERENCES [Usuario] ([usrId]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Stored Procedures */


GO
